### PR TITLE
Undo py3.6 breaking change. Add requests library to installation

### LINKED ISSUE #20: Fails to build with Python 3.6
Hmm think we have a regression - forgot to raise at the time that the change made recently breaks Python 3.6 (Ubuntu 18.04 default - and the provided Dockerfile that bases off this) support - specifically this: 0074a6b
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/optsoft/ALBUS/share/python/MS_Iono_functions.py", line 56, in <module>
    import GPS_stations
  File "/optsoft/ALBUS/share/python/GPS_stations.py", line 520, in <module>
    GPS_stations = fill_standard_stations()
  File "/optsoft/ALBUS/share/python/GPS_stations.py", line 479, in fill_standard_stations
    GPS_dict = fill_GPS_station_dict(GPS_dict, sys_file)
  File "/optsoft/ALBUS/share/python/GPS_stations.py", line 246, in fill_GPS_station_dict
    raise e
  File "/optsoft/ALBUS/share/python/GPS_stations.py", line 221, in fill_GPS_station_dict
    for line in fp:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5073: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by bennahugo**
Fixes #20

### CODE REVIEW

**Comment by bennahugo** [comment]
It is not UTF8 encoded -- there is some weird accented characters in there
One of the location names had a non-ascii character in there for instance and this caused it to break. The only way to read that is in binary mode and then stripping anything that is not 127 or less out of it.

**Comment by bennahugo** [comment]
Here is the offending line
>>> list(filter(lambda l: any(map(lambda x: x > 127, l)), lines))
[b' bscn  A BSCN00FRA P         Besan\xc3\xa7on   FRA  05 59 21.8   47 14 48.8    358.6 \n', b' spt7  A SPT700SWE P            Bor\xc3\xa5s   SWE  12 53 29.2   57 42 53.7    221.1 \n']

It appears as follows
```
bscn  A BSCN00FRA P         Besançon   FRA  05 59 21.8   47 14 48.8    358.6 
```

**Comment by twillis449** [comment]
Ah - OK :) - might be a few other things like this in either the GNSS global stations or the EUREF stations.

**Comment by twillis449** [comment]
BTW - if we ever get around to updating and submitting the ALBUS reference paper I will be adding your name to the list of authors. You've already done a lot more than some of the original authors. :)

**Comment by twillis449** [comment]
BTW - when you upgrade to Python 3.10 this issue will go away as I guess it seems to have non-ascii understanding built in.

**Pull request merged**
